site_name: Benjamin Saupp 
site_url: https://sitename.example
theme:
  features:
    - content.code.copy
    - navigation.footer
  name: material
  icon:
    logo: material/library
    
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  font:
    text: Albert Sans
    code: Share Tech Mono
markdown_extensions:
  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition
  - pymdownx.details



# extra:
#   social:
#     - icon: simple/youtube
#       link: https://youtube.com/@james-willett
#     - icon: simple/linkedin
#       link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2025 Benjamin Saupp